addReviewers: true
addAssignees: true

# If true, adds reviewers/assignees only if PR author is not in the list
skipUsers:
  - dependabot[bot]

reviewers:
  - LoserCheems
  - SNHuan
  - wubingheng111

assignees:
  - LoserCheems
  - SNHuan
  - wubingheng111

numberOfReviewers: 8
